# Generated by Django 4.1.3 on 2023-02-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.CharField(max_length=50)),
                ('risk_score', models.CharField(max_length=50)),
                ('phishing', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=200)),
                ('malware', models.CharField(max_length=200)),
                ('screenshot', models.ImageField(upload_to='screenshots/')),
            ],
        ),
        migrations.CreateModel(
            name='UrlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
